Fix memory leak
IndexError: list index out of range was happening (around line 543) and causing memory leaks on my sistem. This modifications fixed the issue.